# model
batch_size: 16
checkpoint_path: ckpts
checkpoint_name: cp-{epoch:04d}.h5
x_path: data/x.data
y_path: data/y.data
data_shape: [[1, 9, 7], [1, 3, 9, 7]]
epochs: 1
checkpoint: none # cp-0099.h5
gpu: [0]
log_path: log
model_format: .h5
model_path: model
split: [0.8, 0.1, 0.1] # training, validation, testing
learning_rate: 0.00001
beta_1: 0.9 # for adam
beta_2: 0.99 # for adam 
hidden_size: 256
nb_attn_heads: 4 # attention heads
ffn_size: 2048 # feed forward layer size
epsilon: 0.000001 # layer norm
dropout_rate: 0.1
weight_decay: 0.0001

# data generator
nb_samples: 2 # size of generated dataset
pt_mean: 32 # processing time mean
pt_stddev: 8 # processing time standard deviation
job_range: [9, 9] # range of jobs for one problem instance 
machine_range: [3, 3] # range of machines for one problem instance 
nb_setup_types: 5 # number of setup types
nb_sanity_checks: 2 # test validity of generated data