batch_size: 16
checkpoint_path: ckpts
checkpoint_name: cp-{epoch:04d}.h5
x_path: data/x.data
y_path: data/y.data
data_shape: [[1, 9, 7], [1, 3, 9, 7]]
epochs: 1
checkpoint: none #cp-0099.h5
gpu: [0]
log_path: log
model_format: .h5
model_path: model
split: [0.8, 0.1, 0.1]
learning_rate: 0.00001
beta_1: 0.9
beta_2: 0.99
hidden_size: 256
nb_attn_heads: 4
ffn_size: 2048
epsilon: 0.000001
dropout_rate: 0.1
weight_decay: 0.0001
